repos:
  # For the Frontend
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.15.0'
    hooks:
      - id: eslint
        additional_dependencies: ['eslint@8.15.0', 'eslint-plugin-vue@8.7.1']
        args: ['--fix']
        files: '\.(ts|vue)$'
        exclude: 'node_modules'
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1'
    hooks:
      - id: prettier
        additional_dependencies: ['prettier@2.7.1']
        args: ['--write','--no-semi']
        files: '\.(ts|vue|css|scss|json|md)$'
        exclude: 'node_modules'

  # For the Backend
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [mccabe, pycodestyle, pyflakes]
        args: [--max-line-length=150, "--ignore=E203,E231,W503"]


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
