version: "3.9"

services:
  # PostgreSQL Database
  db:
    image: postgres
    container_name: nextshape_db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Django Backend
  backend:
    build:
      context: ./WS
    container_name: nextshape_backend
    depends_on:
      - db
    environment:
      ENV: ${ENV}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - ./WS:/app
    ports:
      - "8000:8000"
    command: ./entrypoint.sh

  # Vue.js Frontend
  frontend:
    build:
      context: ./UI
    container_name: nextshape_frontend
    environment:
      - NODE_ENV=prod
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pg_data:
