version: "3.9"

services:
  db:
    image: postgres
    container_name: nextshape_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: WS/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: nextshape_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ./entrypoint.sh

volumes:
  pg_data:
