version: "3.9"

services:
  # PostgreSQL Database
  db:
    image: postgres
    container_name: nextshape_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Django Backend
  backend:
    build:
      context: ./WS
    env_file: .env
    container_name: nextshape_backend
    depends_on:
      - db
    volumes:
      - ./WS:/app
    ports:
      - "8000:8000"
    command: ./entrypoint.sh

  # Vue.js Frontend
  frontend:
    build:
      context: ./UI
      args:
        VITE_API_URL: ${VITE_API_URL}
    env_file: .env
    container_name: nextshape_frontend
    environment:
      - NODE_ENV=prod
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pg_data:
