# Generated by Django 5.1.5 on 2025-02-18 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                ("height", models.FloatField()),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Homme"), ("F", "Femme")], max_length=10
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sédentaire (peu ou pas d'exercice)"),
                            ("light", "Léger (1-3 séances de sport par semaine)"),
                            ("moderate", "Modéré (3-5 séances de sport par semaine)"),
                            ("active", "Actif (sport quotidien ou travail physique)"),
                            (
                                "very_active",
                                "Très actif (athlète ou métier très physique)",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
