# Generated by Django 5.1.5 on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_usernutritionpreferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationcode",
            name="context",
            field=models.CharField(
                choices=[
                    ("registration", "registration"),
                    ("reset_password", "reset_password"),
                ],
                default="registration",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailverificationcode",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailverificationcode",
            name="used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
