# Generated by Django 5.1.5 on 2025-07-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_progressrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(default="H", max_length=1),
        ),
    ]
