name: NextShape CI - Dev
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning the repository
        uses: actions/checkout@v3

      - name: Installing Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Testing on Docker
        run: |
          docker-compose -f docker-compose.test.yml up --abort-on-container-exit --build
